name: super-linter

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  super-linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go generate
        run: |
          go generate ./...

      - name: Super-Linter
        uses: github/super-linter@v3.14.3
